<?php
/**
* ReadyScript (http://readyscript.ru)
*
* @copyright Copyright (c) ReadyScript lab. (http://readyscript.ru)
* @license http://readyscript.ru/licenseAgreement/
*/
namespace Shop\Model\DeliveryType;

class EmsLocations
{
    
    public static $cities = array(
        'city--abakan'          => 'АБАКАН',
        'city--anadyr'          => 'АНАДЫРЬ',
        'city--anapa'           => 'АНАПА',
        'city--arhangelsk'      => 'АРХАНГЕЛЬСК',
        'city--astrahan'        => 'АСТРАХАНЬ',
        'city--bajkonur'        => 'БАЙКОНУР',
        'city--barnaul'         => 'БАРНАУЛ',
        'city--belgorod'        => 'БЕЛГОРОД',
        'city--birobidzhan'     => 'БИРОБИДЖАН',
        'city--blagoveshhensk'  => 'БЛАГОВЕЩЕНСК',
        'city--brjansk'         => 'БРЯНСК',
        'city--velikij-novgorod' => 'ВЕЛИКИЙ НОВГОРОД',
        'city--vladivostok'     => 'ВЛАДИВОСТОК',
        'city--vladikavkaz'     => 'ВЛАДИКАВКАЗ',
        'city--vladimir'        => 'ВЛАДИМИР',
        'city--volgograd'       => 'ВОЛГОГРАД',
        'city--vologda'         => 'ВОЛОГДА',
        'city--vorkuta'         => 'ВОРКУТА',
        'city--voronezh'        => 'ВОРОНЕЖ',
        'city--gorno-altajsk'   => 'ГОРНО-АЛТАЙСК',
        'city--groznyj'         => 'ГРОЗНЫЙ',
        'city--dudinka'         => 'ДУДИНКА',
        'city--ekaterinburg'    => 'ЕКАТЕРИНБУРГ',
        'city--elizovo'         => 'ЕЛИЗОВО',
        'city--ivanovo'         => 'ИВАНОВО',
        'city--izhevsk'         => 'ИЖЕВСК',
        'city--irkutsk'         => 'ИРКУТСК',
        'city--ioshkar-ola'     => 'ЙОШКАР-ОЛА',
        'city--kazan'           => 'КАЗАНЬ',
        'city--kaliningrad'     => 'КАЛИНИНГРАД',
        'city--kaluga'          => 'КАЛУГА',
        'city--kemerovo'        => 'КЕМЕРОВО',
        'city--kirov'           => 'КИРОВ',
        'city--kostomuksha'     => 'КОСТОМУКША',
        'city--kostroma'        => 'КОСТРОМА',
        'city--krasnodar'       => 'КРАСНОДАР',
        'city--krasnojarsk'     => 'КРАСНОЯРСК',
        'city--kurgan'          => 'КУРГАН',
        'city--kursk'           => 'КУРСК',
        'city--kyzyl'           => 'КЫЗЫЛ',
        'city--lipeck'          => 'ЛИПЕЦК',
        'city--magadan'         => 'МАГАДАН',
        'city--magnitogorsk'    => 'МАГНИТОГОРСК',
        'city--majkop'          => 'МАЙКОП',
        'city--mahachkala'      => 'МАХАЧКАЛА',
        'city--mineralnye-vody' => 'МИНЕРАЛЬНЫЕ ВОДЫ',
        'city--mirnyj'          => 'МИРНЫЙ',
        'city--moskva'          => 'МОСКВА',
        'city--murmansk'        => 'МУРМАНСК',
        'city--mytishhi'        => 'МЫТИЩИ',
        'city--naberezhnye-chelny' => 'НАБЕРЕЖНЫЕ ЧЕЛНЫ',
        'city--nadym'           => 'НАДЫМ',
        'city--nazran'          => 'НАЗРАНЬ',
        'city--nalchik'         => 'НАЛЬЧИК',
        'city--narjan-mar'      => 'НАРЬЯН-МАР',
        'city--nerjungri'       => 'НЕРЮНГРИ',
        'city--neftejugansk'    => 'НЕФТЕЮГАНСК',
        'city--nizhnevartovsk'  => 'НИЖНЕВАРТОВСК',
        'city--nizhnij-novgorod' => 'НИЖНИЙ НОВГОРОД',
        'city--novokuzneck'     => 'НОВОКУЗНЕЦК',
        'city--novorossijsk'    => 'НОВОРОССИЙСК',
        'city--novosibirsk'     => 'НОВОСИБИРСК',
        'city--novyj-urengoj'   => 'НОВЫЙ УРЕНГОЙ',
        'city--norilsk'         => 'НОРИЛЬСК',
        'city--nojabrsk'        => 'НОЯБРЬСК',
        'city--omsk'            => 'ОМСК',
        'city--orel'            => 'ОРЁЛ',
        'city--orenburg'        => 'ОРЕНБУРГ',
        'city--penza'           => 'ПЕНЗА',
        'city--perm'            => 'ПЕРМЬ',
        'city--petrozavodsk'    => 'ПЕТРОЗАВОДСК',
        'city--petropavlovsk-kamchatskij' => 'ПЕТРОПАВЛОВСК-КАМЧАТСКИЙ',
        'city--pskov'           => 'ПСКОВ',
        'city--rostov-na-donu'  => 'РОСТОВ-НА-ДОНУ',
        'city--rjazan'          => 'РЯЗАНЬ',
        'city--salehard'        => 'САЛЕХАРД',
        'city--samara'          => 'САМАРА',
        'city--sankt-peterburg' => 'САНКТ-ПЕТЕРБУРГ',
        'city--saransk'         => 'САРАНСК',
        'city--saratov'         => 'САРАТОВ',
        'city--smolensk'        => 'СМОЛЕНСК',
        'city--sochi'           => 'СОЧИ',
        'city--stavropol'       => 'СТАВРОПОЛЬ',
        'city--strezhevoj'      => 'СТРЕЖЕВОЙ',
        'city--surgut'          => 'СУРГУТ',
        'city--syktyvkar'       => 'СЫКТЫВКАР',
        'city--tambov'          => 'ТАМБОВ',
        'city--tver'            => 'ТВЕРЬ',
        'city--toljatti'        => 'ТОЛЬЯТТИ',
        'city--tomsk'           => 'ТОМСК',
        'city--tula'            => 'ТУЛА',
        'city--tynda'           => 'ТЫНДА',
        'city--tjumen'          => 'ТЮМЕНЬ',
        'city--ulan-udje'       => 'УЛАН-УДЭ',
        'city--uljanovsk'       => 'УЛЬЯНОВСК',
        'city--usinsk'          => 'УСИНСК',
        'city--ufa'             => 'УФА',
        'city--uhta'            => 'УХТА',
        'city--khabarovsk'      => 'ХАБАРОВСК',
        'city--khanty-mansijsk' => 'ХАНТЫ-МАНСИЙСК',
        'city--kholmsk'         => 'ХОЛМСК',
        'city--cheboksary'      => 'ЧЕБОКСАРЫ',
        'city--cheljabinsk'     => 'ЧЕЛЯБИНСК',
        'city--cherepovec'      => 'ЧЕРЕПОВЕЦ',
        'city--cherkessk'       => 'ЧЕРКЕССК',
        'city--chita'           => 'ЧИТА',
        'city--elista'          => 'ЭЛИСТА',
        'city--yuzhno-sahalinsk' => 'ЮЖНО-САХАЛИНСК',
        'city--yakutsk'         => 'ЯКУТСК',
        'city--yaroslavl'       => 'ЯРОСЛАВЛЬ',    
    );
}
?>